#include <surfel_tracer/bvh.h>

#include <optix.h>
#include <optix_stubs.h>
#include <optix_function_table_definition.h>
#include <optix_stack_size.h>

// Custom optix toolchain stuff
#include "optix/gaussiantrace_forward.h"
#include "optix/gaussiantrace_backward.h"
#include "optix/gaussiantrace_intersection_test.h"

#include "optix/program.h"

// Compiled optix program PTX generated by cmake and wrapped in a C
// header by bin2c.
namespace optix_ptx {
	#include <optix_ptx.h>
}

#include <stack>
#include <algorithm>
#include <cstring>
#include <iostream>
#include <cstdio>
#include <vector>

using namespace surfel_tracer;


namespace surfel_tracer {

OptixDeviceContext g_optix;

namespace optix {
	static void context_log_callback(
		unsigned int level, const char* tag, const char* message, void*) {
		fprintf(stderr, "[OptiX][%u][%s] %s\n", level, tag, message);
	}

	bool initialize() {
		static bool ran_before = false;
		static bool is_optix_initialized = false;
		if (ran_before) {
			return is_optix_initialized;
		}

		ran_before = true;

		// Initialize CUDA with a no-op call to the the CUDA runtime API
		CUDA_CHECK_THROW(cudaFree(nullptr));

		try {
			// Initialize the OptiX API, loading all API entry points
			OPTIX_CHECK_THROW(optixInit());

			// Specify options for this context. We will use the default options.
			OptixDeviceContextOptions options = {};
			options.logCallbackFunction = &context_log_callback;
			options.logCallbackLevel = 2;

			// Associate a CUDA context (and therefore a specific GPU) with this
			// device context
			CUcontext cuCtx = 0; // NULL means take the current active context

			OPTIX_CHECK_THROW(optixDeviceContextCreate(cuCtx, &options, &g_optix));
		} catch (std::exception& e) {
			return false;
		}

		is_optix_initialized = true;
		return true;
	}

	void destroy(){
		OPTIX_CHECK_THROW(optixDeviceContextDestroy(g_optix));
	}

	class Gas {
	public:
		Gas(const float* triangles, int n_triangles, OptixDeviceContext optix,
			cudaStream_t stream, bool static_bvh,
			uint32_t primitive_index_offset = 0)
			: m_static(static_bvh), m_n_triangles(n_triangles) {
			if (n_triangles <= 0) {
				throw std::runtime_error("OptiX GAS requires at least one triangle");
			}
			// Specify options for the build. We use default options for simplicity.
			accel_options.buildFlags = static_bvh
				? (OPTIX_BUILD_FLAG_PREFER_FAST_TRACE |
				   OPTIX_BUILD_FLAG_ALLOW_COMPACTION)
				: OPTIX_BUILD_FLAG_ALLOW_UPDATE;
			accel_options.operation = OPTIX_BUILD_OPERATION_BUILD;

			// Populate the build input struct with our triangle data as well as
			// information about the sizes and types of our data
			const uint32_t triangle_input_flags[1] = { OPTIX_GEOMETRY_FLAG_NONE };

			CUdeviceptr d_triangles = (CUdeviceptr)(uintptr_t)triangles;

			triangle_input.type = OPTIX_BUILD_INPUT_TYPE_TRIANGLES;
			triangle_input.triangleArray.vertexFormat = OPTIX_VERTEX_FORMAT_FLOAT3;
			triangle_input.triangleArray.numVertices = (uint32_t)n_triangles*3;
			triangle_input.triangleArray.vertexBuffers = &d_triangles;
			triangle_input.triangleArray.flags = triangle_input_flags;
			triangle_input.triangleArray.numSbtRecords = 1;
			// optixGetPrimitiveIndex() includes this offset.  Giving each GAS a
			// disjoint primitive interval lets the existing flat primitive->GS
			// lookup remain valid under an IAS without changing alpha blending.
			triangle_input.triangleArray.primitiveIndexOffset =
				primitive_index_offset;

			// Query OptiX for the memory requirements for our GAS
			OPTIX_CHECK_THROW(optixAccelComputeMemoryUsage(optix, &accel_options, &triangle_input, 1, &gas_buffer_sizes));

			// Allocate device memory for the scratch space buffer as well
			// as the GAS itself
			gas_tmp_buffer.resize(static_bvh
				? gas_buffer_sizes.tempSizeInBytes
				: std::max(gas_buffer_sizes.tempSizeInBytes,
					gas_buffer_sizes.tempUpdateSizeInBytes));
			m_gas_gpu_buffer.resize(gas_buffer_sizes.outputSizeInBytes);

			GPUMemory<uint64_t> compacted_size_gpu;
			OptixAccelEmitDesc emit_desc = {};
			if (static_bvh) {
				compacted_size_gpu.resize(1);
				emit_desc.type = OPTIX_PROPERTY_TYPE_COMPACTED_SIZE;
				emit_desc.result = (CUdeviceptr)(uintptr_t)compacted_size_gpu.data();
			}

			OPTIX_CHECK_THROW(optixAccelBuild(
				optix,
				stream,
				&accel_options,
				&triangle_input,
				1,           // num build inputs
				(CUdeviceptr)(uintptr_t)gas_tmp_buffer.data(),
				gas_buffer_sizes.tempSizeInBytes,
				(CUdeviceptr)(uintptr_t)m_gas_gpu_buffer.data(),
				gas_buffer_sizes.outputSizeInBytes,
				&m_gas_handle, // Output handle to the struct
				static_bvh ? &emit_desc : nullptr,
				static_bvh ? 1 : 0
			));

			if (static_bvh) {
				uint64_t compacted_size = 0;
				CUDA_CHECK_THROW(cudaMemcpyAsync(
					&compacted_size, compacted_size_gpu.data(), sizeof(uint64_t),
					cudaMemcpyDeviceToHost, stream));
				CUDA_CHECK_THROW(cudaStreamSynchronize(stream));
				if (compacted_size > 0 &&
					compacted_size < m_gas_gpu_buffer.get_bytes()) {
					GPUMemory<char> compacted_buffer(compacted_size);
					OptixTraversableHandle compacted_handle = 0;
					OPTIX_CHECK_THROW(optixAccelCompact(
						optix, stream, m_gas_handle,
						(CUdeviceptr)(uintptr_t)compacted_buffer.data(),
						compacted_size, &compacted_handle));
					CUDA_CHECK_THROW(cudaStreamSynchronize(stream));
					m_gas_gpu_buffer = std::move(compacted_buffer);
					m_gas_handle = compacted_handle;
				}
				// Static GAS never needs the update scratch buffer again.
				gas_tmp_buffer.resize(0);
			}
		}

		void update(const float* triangles, int n_triangles, OptixDeviceContext optix, cudaStream_t stream) {
			if (m_static) {
				throw std::runtime_error("Cannot update a compacted static OptiX GAS");
			}
			if (n_triangles != m_n_triangles) {
				throw std::runtime_error(
					"OptiX GAS update requires an unchanged triangle count");
			}
			// Specify options for the build. We use default options for simplicity.
			accel_options.operation = OPTIX_BUILD_OPERATION_UPDATE;

			// Populate the build input struct with our triangle data as well as
			// information about the sizes and types of our data
			const uint32_t triangle_input_flags[1] = { OPTIX_GEOMETRY_FLAG_NONE };

			CUdeviceptr d_triangles = (CUdeviceptr)(uintptr_t)triangles;
			triangle_input.triangleArray.vertexBuffers = &d_triangles;
			triangle_input.triangleArray.flags = triangle_input_flags;

			// // Query OptiX for the memory requirements for our GAS
			// OPTIX_CHECK_THROW(optixAccelComputeMemoryUsage(optix, &accel_options, &triangle_input, 1, &gas_buffer_sizes));

			// // Allocate device memory for the scratch space buffer as well
			// // as the GAS itself
			// gas_tmp_buffer.resize(gas_buffer_sizes.tempSizeInBytes);
			// m_gas_gpu_buffer.resize(gas_buffer_sizes.outputSizeInBytes);

			OPTIX_CHECK_THROW(optixAccelBuild(
				optix,
				stream,
				&accel_options,
				&triangle_input,
				1,           // num build inputs
				(CUdeviceptr)(uintptr_t)gas_tmp_buffer.data(),
				gas_buffer_sizes.tempUpdateSizeInBytes,
				(CUdeviceptr)(uintptr_t)m_gas_gpu_buffer.data(),
				gas_buffer_sizes.outputSizeInBytes,
				&m_gas_handle, // Output handle to the struct
				nullptr,       // emitted property list
				0              // num emitted properties
			));
		}

		OptixTraversableHandle handle() const {
			return m_gas_handle;
		}
		bool is_static() const { return m_static; }

	private:
		OptixTraversableHandle m_gas_handle;
		GPUMemory<char> m_gas_gpu_buffer;
		OptixAccelBuildOptions accel_options = {};
		OptixBuildInput triangle_input = {};
		OptixAccelBufferSizes gas_buffer_sizes;
		GPUMemory<char> gas_tmp_buffer;
		bool m_static = false;
		int m_n_triangles = 0;
	};

	class Ias {
	public:
		Ias(const std::vector<Gas*>& gases, const float* transforms,
			OptixDeviceContext optix, cudaStream_t stream) : m_gases(gases) {
			if (m_gases.empty()) {
				throw std::runtime_error("IAS requires at least one GAS");
			}
			accel_options.buildFlags =
				OPTIX_BUILD_FLAG_ALLOW_UPDATE |
				OPTIX_BUILD_FLAG_PREFER_FAST_TRACE;
			accel_options.operation = OPTIX_BUILD_OPERATION_BUILD;
			instances_gpu.resize(m_gases.size());
			copy_instances(transforms, stream);

			build_input.type = OPTIX_BUILD_INPUT_TYPE_INSTANCES;
			build_input.instanceArray.instances =
				(CUdeviceptr)(uintptr_t)instances_gpu.data();
			build_input.instanceArray.numInstances =
				static_cast<unsigned int>(m_gases.size());
			OPTIX_CHECK_THROW(optixAccelComputeMemoryUsage(
				optix, &accel_options, &build_input, 1, &buffer_sizes));
			tmp_buffer.resize(std::max(
				buffer_sizes.tempSizeInBytes,
				buffer_sizes.tempUpdateSizeInBytes));
			output_buffer.resize(buffer_sizes.outputSizeInBytes);
			build(optix, stream, OPTIX_BUILD_OPERATION_BUILD);
		}

		void update(const float* transforms, int n_instances,
			OptixDeviceContext optix, cudaStream_t stream) {
			if (n_instances != static_cast<int>(m_gases.size())) {
				throw std::runtime_error("IAS transform count changed");
			}
			copy_instances(transforms, stream);
			build(optix, stream, OPTIX_BUILD_OPERATION_UPDATE);
		}

		OptixTraversableHandle handle() const { return m_handle; }

	private:
		void copy_instances(const float* transforms, cudaStream_t stream) {
			host_instances.resize(m_gases.size());
			for (size_t i = 0; i < m_gases.size(); ++i) {
				OptixInstance instance = {};
				std::memcpy(instance.transform, transforms + i * 12,
					12 * sizeof(float));
				instance.instanceId = static_cast<unsigned int>(i);
				instance.sbtOffset = 0;
				instance.visibilityMask = 255;
				instance.flags = OPTIX_INSTANCE_FLAG_NONE;
				instance.traversableHandle = m_gases[i]->handle();
				host_instances[i] = instance;
			}
			CUDA_CHECK_THROW(cudaMemcpyAsync(
				instances_gpu.data(), host_instances.data(),
				host_instances.size() * sizeof(OptixInstance),
				cudaMemcpyHostToDevice, stream));
		}

		void build(OptixDeviceContext optix, cudaStream_t stream,
			OptixBuildOperation operation) {
			accel_options.operation = operation;
			const size_t tmp_size = operation == OPTIX_BUILD_OPERATION_UPDATE
				? buffer_sizes.tempUpdateSizeInBytes
				: buffer_sizes.tempSizeInBytes;
			OPTIX_CHECK_THROW(optixAccelBuild(
				optix, stream, &accel_options, &build_input, 1,
				(CUdeviceptr)(uintptr_t)tmp_buffer.data(), tmp_size,
				(CUdeviceptr)(uintptr_t)output_buffer.data(),
				buffer_sizes.outputSizeInBytes, &m_handle, nullptr, 0));
		}

		std::vector<Gas*> m_gases;
		std::vector<OptixInstance> host_instances;
		GPUMemory<OptixInstance> instances_gpu;
		GPUMemory<char> tmp_buffer;
		GPUMemory<char> output_buffer;
		OptixBuildInput build_input = {};
		OptixAccelBuildOptions accel_options = {};
		OptixAccelBufferSizes buffer_sizes = {};
		OptixTraversableHandle m_handle = 0;
	};
}

class TriangleBvh : public TriangleBvhBase {
public:
	TriangleBvh() {
		m_optix.available = optix::initialize();
		m_optix.gaussiantrace_forward = make_forward_program("__raygen__rg", false);
		m_optix.gaussiantrace_material4 = make_forward_program("__raygen__material4", false);
		m_optix.gaussiantrace_material5 = make_forward_program("__raygen__material5", false);
		m_optix.gaussiantrace_visibility = make_forward_program("__raygen__visibility", false);
		m_optix.gaussiantrace_backward = make_backward_program(false);
		m_optix.gaussiantrace_intersection_test = make_intersection_program(false);
	}

	~TriangleBvh() {
		if (m_optix.available) {
			optix::destroy();
			printf("OptiX destroyed.\n");
		}
	}

	void intersection_test(
		uint32_t n_elements, const glm::vec3* rays_o, const glm::vec3* rays_d,
		const int* gs_idxs, const glm::vec3* means3D, const float* opacity,
		const glm::vec3* ru, const glm::vec3* rv, const glm::vec3* normals,
		bool* intersection, cudaStream_t stream) override {
		auto* program = using_ias()
			? m_optix.ias_gaussiantrace_intersection_test.get()
			: m_optix.gaussiantrace_intersection_test.get();
		program->invoke(
			{rays_o, rays_d, gs_idxs, means3D, opacity, ru, rv, normals,
			 intersection, active_handle()},
			{n_elements, 1, 1}, stream);
	}

	void gaussian_trace_forward(
		uint32_t n_elements, const int S, const glm::vec3* rays_o,
		const glm::vec3* rays_d, const int* gs_idxs, const glm::vec3* means3D,
		const float* opacity, const glm::vec3* ru, const glm::vec3* rv,
		const glm::vec3* normals, const float* features, const glm::vec3* shs,
		glm::vec3* color, glm::vec3* normal, float* feature, float* depth,
		float* alpha, const float alpha_min, const float transmittance_min,
		const int deg, const int max_coeffs, const bool back_culling,
		const int trace_mode, int* diagnostics, const bool diagnostics_enabled,
		cudaStream_t stream) override {
		optix::Program<Gaussiantrace_forward>* program = nullptr;
		if (trace_mode == 0) {
			program = using_ias() ? m_optix.ias_gaussiantrace_forward.get()
				: m_optix.gaussiantrace_forward.get();
		} else if (trace_mode == 1 && S == 4) {
			program = using_ias() ? m_optix.ias_gaussiantrace_material4.get()
				: m_optix.gaussiantrace_material4.get();
		} else if (trace_mode == 1 && S == 5) {
			program = using_ias() ? m_optix.ias_gaussiantrace_material5.get()
				: m_optix.gaussiantrace_material5.get();
		} else if (trace_mode == 2) {
			program = using_ias() ? m_optix.ias_gaussiantrace_visibility.get()
				: m_optix.gaussiantrace_visibility.get();
		} else {
			throw std::runtime_error("Unsupported Gaussian trace mode/feature count");
		}
		program->invoke(
			{rays_o, rays_d, gs_idxs, means3D, opacity, ru, rv, normals,
			 features, shs, color, normal, feature, depth, alpha, alpha_min,
			 transmittance_min, deg, max_coeffs, S, back_culling, diagnostics,
			 diagnostics_enabled, active_handle()},
			{n_elements, 1, 1}, stream);
	}

	void gaussian_trace_backward(
		uint32_t n_elements, const int S, const glm::vec3* rays_o,
		const glm::vec3* rays_d, const int* gs_idxs, const glm::vec3* means3D,
		const float* opacity, const glm::vec3* ru, const glm::vec3* rv,
		const glm::vec3* normals, const float* features, const glm::vec3* shs,
		const glm::vec3* color, const glm::vec3* normal, const float* feature,
		const float* depth, const float* alpha, glm::vec3* grad_rays_o,
		glm::vec3* grad_rays_d, glm::vec3* grad_means3D, float* grad_opacity,
		glm::vec3* grad_ru, glm::vec3* grad_rv, glm::vec3* grad_normals,
		float* grad_features, glm::vec3* grad_shs, const glm::vec3* grad_color,
		const glm::vec3* grad_normal, const float* grad_feature,
		const float* grad_depth, const float* grad_alpha, const float alpha_min,
		const float transmittance_min, const int deg, const int max_coeffs,
		const bool back_culling, cudaStream_t stream) override {
		auto* program = using_ias() ? m_optix.ias_gaussiantrace_backward.get()
			: m_optix.gaussiantrace_backward.get();
		program->invoke(
			{rays_o, rays_d, gs_idxs, means3D, opacity, ru, rv, normals,
			 features, shs, color, normal, feature, depth, alpha, grad_rays_o,
			 grad_rays_d, grad_means3D, grad_opacity, grad_ru, grad_rv,
			 grad_normals, grad_features, grad_shs, grad_color, grad_normal,
			 grad_feature, grad_depth, grad_alpha, alpha_min, transmittance_min,
			 deg, max_coeffs, S, back_culling, active_handle()},
			{n_elements, 1, 1}, stream);
	}

	void build_bvh(const float* triangles, int n_triangles, bool static_bvh,
		cudaStream_t stream) override {
		m_optix.ias.reset();
		m_optix.ias_gases.clear();
		m_optix.gas = std::make_unique<optix::Gas>(
			triangles, n_triangles, g_optix, stream, static_bvh);
	}

	void update_bvh(const float* triangles, int n_triangles,
		cudaStream_t stream) override {
		if (!m_optix.gas || using_ias()) {
			throw std::runtime_error("Legacy GAS update requested while IAS is active");
		}
		m_optix.gas->update(triangles, n_triangles, g_optix, stream);
	}

	void build_ias(
		const float* triangles, const int64_t* triangle_offsets,
		const bool* static_flags, const float* transforms,
		int n_instances, cudaStream_t stream) override {
		if (n_instances <= 0) {
			throw std::runtime_error("IAS requires at least one instance");
		}
		ensure_ias_programs();
		m_optix.gas.reset();
		m_optix.ias.reset();
		m_optix.ias_gases.clear();
		m_optix.ias_gases.reserve(n_instances);
		for (int i = 0; i < n_instances; ++i) {
			const int64_t begin = triangle_offsets[i];
			const int64_t end = triangle_offsets[i + 1];
			if (begin < 0 || end <= begin) {
				throw std::runtime_error(
					"IAS triangle offsets must be strictly increasing");
			}
			if (end > static_cast<int64_t>(UINT32_MAX)) {
				throw std::runtime_error(
					"IAS global primitive index exceeds OptiX uint32 range");
			}
			m_optix.ias_gases.emplace_back(std::make_unique<optix::Gas>(
				triangles + begin * 9, static_cast<int>(end - begin),
				g_optix, stream, static_flags[i], static_cast<uint32_t>(begin)));
		}
		std::vector<optix::Gas*> gas_ptrs;
		gas_ptrs.reserve(m_optix.ias_gases.size());
		for (auto& gas : m_optix.ias_gases) {
			gas_ptrs.push_back(gas.get());
		}
		m_optix.ias = std::make_unique<optix::Ias>(
			gas_ptrs, transforms, g_optix, stream);
	}

	void update_ias_gas(int instance_index, const float* triangles,
		int n_triangles, cudaStream_t stream) override {
		if (!using_ias() || instance_index < 0 ||
			instance_index >= static_cast<int>(m_optix.ias_gases.size())) {
			throw std::runtime_error("Invalid IAS GAS instance index");
		}
		auto& gas = m_optix.ias_gases[instance_index];
		if (gas->is_static()) {
			throw std::runtime_error("Cannot update an IAS static GAS");
		}
		gas->update(triangles, n_triangles, g_optix, stream);
	}

	void update_ias_transforms(const float* transforms, int n_instances,
		cudaStream_t stream) override {
		if (!using_ias()) {
			throw std::runtime_error("IAS transform update requested before build");
		}
		m_optix.ias->update(transforms, n_instances, g_optix, stream);
	}

private:
	static constexpr unsigned int ias_graph_flags() {
		return OPTIX_TRAVERSABLE_GRAPH_FLAG_ALLOW_SINGLE_LEVEL_INSTANCING;
	}

	std::unique_ptr<optix::Program<Gaussiantrace_forward>> make_forward_program(
		const char* entry, bool ias) {
		return std::make_unique<optix::Program<Gaussiantrace_forward>>(
			(const char*)optix_ptx::gaussiantrace_forward_ptx,
			sizeof(optix_ptx::gaussiantrace_forward_ptx), g_optix, entry,
			ias ? ias_graph_flags()
				: OPTIX_TRAVERSABLE_GRAPH_FLAG_ALLOW_SINGLE_GAS,
			ias ? 2u : 1u);
	}

	std::unique_ptr<optix::Program<Gaussiantrace_backward>> make_backward_program(
		bool ias) {
		return std::make_unique<optix::Program<Gaussiantrace_backward>>(
			(const char*)optix_ptx::gaussiantrace_backward_ptx,
			sizeof(optix_ptx::gaussiantrace_backward_ptx), g_optix,
			"__raygen__rg", ias ? ias_graph_flags()
				: OPTIX_TRAVERSABLE_GRAPH_FLAG_ALLOW_SINGLE_GAS,
			ias ? 2u : 1u);
	}

	std::unique_ptr<optix::Program<Gaussiantrace_intersection_test>>
	make_intersection_program(bool ias) {
		return std::make_unique<optix::Program<Gaussiantrace_intersection_test>>(
			(const char*)optix_ptx::gaussiantrace_intersection_test_ptx,
			sizeof(optix_ptx::gaussiantrace_intersection_test_ptx), g_optix,
			"__raygen__rg", ias ? ias_graph_flags()
				: OPTIX_TRAVERSABLE_GRAPH_FLAG_ALLOW_SINGLE_GAS,
			ias ? 2u : 1u);
	}

	void ensure_ias_programs() {
		if (m_optix.ias_gaussiantrace_forward) {
			return;
		}
		m_optix.ias_gaussiantrace_forward = make_forward_program("__raygen__rg", true);
		m_optix.ias_gaussiantrace_material4 = make_forward_program("__raygen__material4", true);
		m_optix.ias_gaussiantrace_material5 = make_forward_program("__raygen__material5", true);
		m_optix.ias_gaussiantrace_visibility = make_forward_program("__raygen__visibility", true);
		m_optix.ias_gaussiantrace_backward = make_backward_program(true);
		m_optix.ias_gaussiantrace_intersection_test = make_intersection_program(true);
	}

	bool using_ias() const { return static_cast<bool>(m_optix.ias); }

	OptixTraversableHandle active_handle() const {
		if (m_optix.ias) return m_optix.ias->handle();
		if (m_optix.gas) return m_optix.gas->handle();
		throw std::runtime_error("OptiX acceleration structure has not been built");
	}

	struct {
		std::unique_ptr<optix::Gas> gas;
		std::vector<std::unique_ptr<optix::Gas>> ias_gases;
		std::unique_ptr<optix::Ias> ias;
		std::unique_ptr<optix::Program<Gaussiantrace_forward>> gaussiantrace_forward;
		std::unique_ptr<optix::Program<Gaussiantrace_forward>> gaussiantrace_material4;
		std::unique_ptr<optix::Program<Gaussiantrace_forward>> gaussiantrace_material5;
		std::unique_ptr<optix::Program<Gaussiantrace_forward>> gaussiantrace_visibility;
		std::unique_ptr<optix::Program<Gaussiantrace_backward>> gaussiantrace_backward;
		std::unique_ptr<optix::Program<Gaussiantrace_intersection_test>> gaussiantrace_intersection_test;
		std::unique_ptr<optix::Program<Gaussiantrace_forward>> ias_gaussiantrace_forward;
		std::unique_ptr<optix::Program<Gaussiantrace_forward>> ias_gaussiantrace_material4;
		std::unique_ptr<optix::Program<Gaussiantrace_forward>> ias_gaussiantrace_material5;
		std::unique_ptr<optix::Program<Gaussiantrace_forward>> ias_gaussiantrace_visibility;
		std::unique_ptr<optix::Program<Gaussiantrace_backward>> ias_gaussiantrace_backward;
		std::unique_ptr<optix::Program<Gaussiantrace_intersection_test>> ias_gaussiantrace_intersection_test;
		bool available = false;
	} m_optix;
};

std::unique_ptr<TriangleBvhBase> TriangleBvhBase::make() {
    return std::unique_ptr<TriangleBvhBase>(new TriangleBvh());
}

}
